const SEND_MESSAGE = 'SEND_MESSAGE'
const MESSAGE_ERROR = 'MESSAGE_ERROR'

const GET_PORTFOLIO = 'GET_PORTFOLIO'
const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR'

const GET_PROFILE = 'GET_PROFILE'
const PROFILE_ERROR = 'PROFILE_ERROR'
